### ISSUE TITLE
[BUG]Camera Stop Working When Camera is Accessed by other app

### ISSUE THREAD

**Issue by albertodurmiendo** [ananjaser1211/FloydQ_8890#74]
**Describe the bug**
Camera app stops working when camera is accessed by other app, this bug shows after opening camera in "Messenger" app but its strange that only back camera is working in messenger app, (I can't switch to front) it says Camera is in use by the other app, after that I closed the messenger app then try my camera app then thus crash occurs.(Can't open the camera app anymore) but it fixed by restarting the device. Just want to report this thinking that this simple crash can help with the development of this ROM.

Thanks! 

**To Reproduce**
1. Open 'Messenger App'
2. Open camera on the app
3. Switch to front camera
4. and then the app says its in use, now you can't access the camera app in home screen

**Expected behavior**
Camera should works normally

**Screenshots**
https://imgur.com/a/Ytgye9n

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - Model: G930FD

**Additional context**

[log_e-Camera.log](https://github.com/ananjaser1211/FloydQ_8890/files/4567487/log_e-Camera.log)

**Comment by ananjaser1211** [comment]
Massager lite or the full one ?

The issue does not seem to happen in the lite version for me

**Comment by albertodurmiendo** [comment]
The full Messenger app

**Comment by ananjaser1211** [comment]
> The full Messenger app

Works as well with the Full messenger app after trying couple times. same with the testers

i think this was just an anomaly and not something that is persistent, so ill close this issue. tho if someone else faces it ill consider reopening it. , But one look at your LOG and there seems to be alot going wrong with it.

Somehow the camera HAL is in a "death" state

`E ExynosCamera3FrameFactoryPreview: [CAM_ID(1)][FactoryFront]-ERR(createNewFrame[1086]):m_initPipelines fail, ret(-38)`

and is throwing this error which really can only happen if the HAL got locked up somehow.  The log also contains significant spam from fingerprint authentication for some reason and other internal crashes in instagram , launcher some smart widget.

Did you clean flash the ROM ? and if you did, did you delete the /sdcard/Android data folder left by pie.

because these crashes are abnormal

**Comment by albertodurmiendo** [comment]
I'm sure that I clean flash the rom because I change my rom to f2fs so there's no reason to left some pie files in my storage. Thank you for checking this

**Comment by albertodurmiendo** [comment]
@ananjaser1211 have you tried enabling "Smart stay" when testing this? I have again a report from device care that my camera is crashed
